MODEL:
  IMG:
    PRETRAIN_CHOICE: "imagenet"
    METRIC_LOSS_TYPE: "triplet"
    IF_LABELSMOOTH: "on"
    IF_WITH_CENTER: "no"
    NAME: "ViT-B-16"
    # NAME: 'RN50'
    STRIDE_SIZE: [16, 16]
    ID_LOSS_WEIGHT: 0.25
    TRIPLET_LOSS_WEIGHT: 1.0
    I2T_LOSS_WEIGHT: 1.0
    SIE_CAMERA: True
    SIE_COE: 1.0
  SKE:
    HIDDEN_DIM: 512
    JOINT_NUM: 17
    TIME_STEP: 8
    K_POS_ENC: 10
    NUM_LAYERS: 10
    N_HEADS: 8
    DROPOUT: 0.3
    USE_POS_ENC: True
    USE_S_PROMPT: True
    USE_T_PROMPT: True
    S_TYPE: "l1"
    T_TYPE: "l1"
    PROMPT_LAMBDA: 0.5
    TEMP_SEQ: 0.1
    # TEMP_SKE: 10.0
    TEMP_SKE: 0.1
    SEQ_LAMBDA: 0.5
    GPC_LAMBDA: 0.5

INPUT:
  SIZE_TRAIN: [256, 128]
  SIZE_TEST: [256, 128]
  PROB: 0.5
  RE_PROB: 0.5
  PADDING: 10
  PIXEL_MEAN: [0.5, 0.5, 0.5]
  PIXEL_STD: [0.5, 0.5, 0.5]
  SEQ_LEN: 8

DATALOADER:
  SAMPLER: "softmax_triplet"
  NUM_INSTANCE: 4
  NUM_WORKERS: 8

SOLVER:
  STAGE1:
    IMS_PER_BATCH: 64
    OPTIMIZER_NAME: "Adam"
    BASE_LR: 0.00035
    WARMUP_LR_INIT: 0.00001
    LR_MIN: 1e-6
    WARMUP_METHOD: "linear"
    WEIGHT_DECAY: 1e-4
    WEIGHT_DECAY_BIAS: 1e-4
    MAX_EPOCHS: 120
    CHECKPOINT_PERIOD: 120
    LOG_PERIOD: 50
    WARMUP_EPOCHS: 5

  STAGE2:
    IMS_PER_BATCH: 16
    OPTIMIZER_NAME: "Adam"
    BASE_LR: 0.000005
    WARMUP_METHOD: "linear"
    WARMUP_ITERS: 10
    WARMUP_FACTOR: 0.1
    WEIGHT_DECAY: 0.0001
    WEIGHT_DECAY_BIAS: 0.0001
    LARGE_FC_LR: False
    MAX_EPOCHS: 80
    CHECKPOINT_PERIOD: 40
    LOG_PERIOD: 50
    EVAL_PERIOD: 2
    BIAS_LR_FACTOR: 2
    STEPS: [30, 50, 70]
    GAMMA: 0.1

TEST:
  EVAL: True
  IMS_PER_BATCH: 1
  RE_RANKING: False
  WEIGHT: ""
  NECK_FEAT: "before"
  FEAT_NORM: "yes"

DATASETS:
  NAMES: ('lsvid')
  ROOT_DIR: ('./VB-Datasets/LS-VID')

OUTPUT_DIR: "./logs/lsvid/test"
